# numpy arrays

In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones((3,4),dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.full((3,4),2.1)

array([[2.1, 2.1, 2.1, 2.1],
       [2.1, 2.1, 2.1, 2.1],
       [2.1, 2.1, 2.1, 2.1]])

In [7]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
???

Object `?` not found.


In [15]:
##random numbers

In [16]:
np.random.random(5)

array([0.41158959, 0.68729524, 0.58097957, 0.18940786, 0.98976894])

In [17]:
np.random.rand(5)

array([0.30383499, 0.69753598, 0.06680901, 0.1107871 , 0.50165564])

In [18]:
np.random.normal(1,2,5)# five obs normal(mean=1,s.deviation=2)

array([ 0.11978486,  0.4608757 ,  1.20028978, -1.99350556, -1.34978821])

In [20]:
np.random.normal(5)

2.9206743586563984

In [21]:
np.random.randint(0,10,size=5) #five obs discrete uniform (0,10)

array([3, 7, 0, 7, 7])

# array attributes

In [22]:
np.random.seed(1)####????
x = np.random.randint(10,size=(3,4,5))
x

array([[[5, 8, 9, 5, 0],
        [0, 1, 7, 6, 9],
        [2, 4, 5, 2, 4],
        [2, 4, 7, 7, 9]],

       [[1, 7, 0, 6, 9],
        [9, 7, 6, 9, 1],
        [0, 1, 8, 8, 3],
        [9, 8, 7, 3, 6]],

       [[5, 1, 9, 3, 4],
        [8, 1, 4, 0, 3],
        [9, 2, 0, 4, 9],
        [2, 7, 7, 9, 8]]])

In [23]:
x.ndim

3

In [24]:
x.shape

(3, 4, 5)

In [25]:
x.size

60

In [26]:
x[0,0,2]

9

In [27]:
# integer array does not accept other data type

In [28]:
x[0,0,2]=1.5

In [30]:
x[0,0,2]

1

# 1D array indexing

In [31]:
x = np.array([2,3,6,1,7,9,8,3,1])
x

array([2, 3, 6, 1, 7, 9, 8, 3, 1])

In [32]:
x.ndim

1

In [33]:
x.shape

(9,)

In [34]:
x[7]

3

In [35]:
x[:3]

array([2, 3, 6])

In [36]:
x[-1]

1

In [37]:
x[-2:]

array([3, 1])

In [38]:
x[2:4]

array([6, 1])

In [39]:
x[::2] # every other element

array([2, 6, 7, 8, 1])

In [40]:
x[5::2]# every other element, starting at index 5

array([9, 3])

# nD arrays

In [41]:
np.random.seed(1)

In [42]:
x2 = np.random.randint(10, size=(3,4))
x2

array([[5, 8, 9, 5],
       [0, 0, 1, 7],
       [6, 9, 2, 4]])

In [43]:
x2[0,:]

array([5, 8, 9, 5])

In [46]:
x2[:,1]

array([8, 0, 9])

In [49]:
x2[:,1].shape

(3,)

In [50]:
x2[:,1].ndim

1

In [51]:
x22=x2[:,1]

In [52]:
x22.reshape(-1,1)##???

array([[8],
       [0],
       [9]])

In [53]:
x22.reshape(-1,1).shape

(3, 1)

In [54]:
x22.reshape(-1,1).ndim

2

In [56]:
x2[:2,:3]

array([[5, 8, 9],
       [0, 0, 1]])

In [57]:
x2[::2]

array([[5, 8, 9, 5],
       [6, 9, 2, 4]])

In [58]:
x2[:,::2]

array([[5, 9],
       [0, 1],
       [6, 2]])

# slice or views